export default {
    SET_DAYS: "SET_DAYS",
    SET_START_DATE: "SET_START_DATE",
    UPDATE_CATEGORIES: "UPDATE_CATEGORIES",
    SET_SCHEDULE_TIME: "SET_SCHEDULE_TIME",
    SET_USER_LOCATION: "SET_USER_LOCATION",
}